# Generated by Django 5.0.3 on 2024-03-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_product_image_url_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
