# Generated by Django 5.0.3 on 2024-03-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0004_remove_product_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_main_image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='main_image_url',
            field=models.URLField(blank=True),
        ),
    ]
