# Generated by Django 5.0.3 on 2024-03-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0005_remove_productimage_is_main_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='main_image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='main_image_url',
            field=models.URLField(blank=True),
        ),
    ]
