# Generated by Django 5.0.3 on 2024-03-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0006_remove_productimage_main_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
