# Generated by Django 5.0.3 on 2024-03-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0009_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/products'),
        ),
    ]
