# Generated by Django 5.0.3 on 2024-03-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0011_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_username',
            field=models.CharField(default='Anonymous', max_length=150),
        ),
    ]
